
/* Drop Tables */

DROP TABLE PROGRESS CASCADE CONSTRAINTS;
DROP TABLE COURSE_VIDEO CASCADE CONSTRAINTS;
DROP TABLE ENROLMENT CASCADE CONSTRAINTS;
DROP TABLE POSTSCRIPTION CASCADE CONSTRAINTS;
DROP TABLE QNA CASCADE CONSTRAINTS;
DROP TABLE COURSE CASCADE CONSTRAINTS;
DROP TABLE DEPT CASCADE CONSTRAINTS;
DROP TABLE LECTURER CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE POINT CASCADE CONSTRAINTS;
DROP TABLE TECH CASCADE CONSTRAINTS;
DROP TABLE STUDENT CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE COURSE
(
	COURSE_NO number(6) CONSTRAINT COURSE_NO_NN NOT NULL,
	COURSE_NAME varchar2(100) CONSTRAINT COURSE_NAME_NN NOT NULL,
	COURSE_SUMMARY varchar2(500) CONSTRAINT COURSE_SUMMARY_NN NOT NULL,
	COURSE_DETAIL varchar2(2000),
	COURSE_POINT number(3,0) CONSTRAINT COURSE_POINT_NN NOT NULL,
	LECTURER_NO number(3,0) CONSTRAINT LECTURER_NO_NN NOT NULL,
	DEPT_NO number(2,0) CONSTRAINT DEPT_NO_NN NOT NULL,
	CONSTRAINT COURSE_NO_PK PRIMARY KEY (COURSE_NO)
);


CREATE TABLE COURSE_VIDEO
(
	COURSE_VIDEO_NO number(4,0) CONSTRAINT COURSE_VIDEO_NO_NN NOT NULL,
	COURSE_VIDEO_LINK varchar2(100) CONSTRAINT COURSE_VIDEO_LINK_NN NOT NULL CONSTRAINT COURSE_VIDEO_LINK_UK UNIQUE,
	COURSE_VIDEO_TITLE varchar2(100) CONSTRAINT COURSE_VIDEO_TITLE_NN NOT NULL,
	COURSE_VIDEO_DESCRIPTION varchar2(500) CONSTRAINT COURSE_VIDEO_DESCRIPTION_NN NOT NULL,
	COURSE_VIDEO_ATTACHED varchar2(500),
	COURSE_VIDEO_PERMIT char(1) DEFAULT 'N',
	COURSE_VIDEO_ORDER number(2,0) CONSTRAINT COURSE_VIDEO_ORDER_NN NOT NULL,
	COURSE_NO number(6) CONSTRAINT COURSE_NO_NN NOT NULL,
	CONSTRAINT COURSE_VIDEO_NO_PK PRIMARY KEY (COURSE_VIDEO_NO)
);


CREATE TABLE DEPT
(
	DEPT_NO number(2,0) CONSTRAINT DEPT_NO_NN NOT NULL,
	DEPT_NAME varchar2(0) CONSTRAINT DEPT_NAME_NN NOT NULL CONSTRAINT DEPT_NAME_UK UNIQUE,
	CONSTRAINT DEPT_NO_PK PRIMARY KEY (DEPT_NO)
);


CREATE TABLE ENROLMENT
(
	ENROLMENT_NO number(4,0) CONSTRAINT ENROLMENT_NO_NN NOT NULL,
	ENROLMENT_START_DATE date DEFAULT SYSDATE CONSTRAINT ENROLMENT_START_DATE_NN NOT NULL,
	STUDENT_NO number(3) CONSTRAINT STUDENT_NO_NN NOT NULL,
	COURSE_NO number(6) CONSTRAINT COURSE_NO_NN NOT NULL,
	CONSTRAINT ENROLMENT_NO_PK PRIMARY KEY (ENROLMENT_NO)
);


CREATE TABLE LECTURER
(
	LECTURER_NO number(3,0) CONSTRAINT LECTURER_NO_NN NOT NULL,
	LECTURER_NAME varchar2(100) CONSTRAINT LECTURER_NAME_NN NOT NULL,
	LECTURER_EMAIL varchar2(256) CONSTRAINT LECTURER_EMAIL_NN NOT NULL CONSTRAINT LECTURER_EMAIL_UK UNIQUE,
	LECTURER_PWD char(64) CONSTRAINT LECTURER_PWD_NN NOT NULL,
	LECTURER_PHONE varchar2(20) CONSTRAINT LECTURER_PHONE_NN NOT NULL,
	LECTURER_CAREER varchar2(200),
	LECTURER_PICTURE varchar2(500),
	LECTURER_PERMIT char(1) DEFAULT 'N',
	USER_TYPE char(1) DEFAULT 'T',
	CONSTRAINT LECTURER_NO_PK PRIMARY KEY (LECTURER_NO)
);


CREATE TABLE NOTICE
(
	NOTICE_NO number(4,0) CONSTRAINT NOTICE_NO_NN NOT NULL,
	NOTICE_TITLE varchar2(100) CONSTRAINT NOTICE_TITLE_NN NOT NULL,
	NOTICE_CONTENT varchar2(2000) CONSTRAINT NOTICE_CONTENT_NN NOT NULL,
	NOTICE_REGDATE date DEFAULT SYSDATE CONSTRAINT NOTICE_REGDATE_NN NOT NULL,
	NOTICE_EXPIREDATE date,
	NOTICE_ACTIVE char(1) DEFAULT 'Y',
	CONSTRAINT NOTICE_NO_PK PRIMARY KEY (NOTICE_NO)
);


CREATE TABLE POINT
(
	POINT_PAYMENT number(5,0) CONSTRAINT POINT_PAYMENT_NN NOT NULL,
	POINT_HISTORY varchar2(150) CONSTRAINT POINT_HISTORY_NN NOT NULL,
	POINT_DATE date DEFAULT SYSDATE CONSTRAINT POINT_DATE_NN NOT NULL,
	STUDENT_NO number(3) CONSTRAINT STUDENT_NO_NN NOT NULL
);


CREATE TABLE POSTSCRIPTION
(
	POSTSCRIPTION_NO number(4,0) CONSTRAINT POSTSCRIPTION_NO_NN NOT NULL,
	POSTSCRIPTION_TITLE varchar2(100) CONSTRAINT POSTSCRIPTION_TITLE_NN NOT NULL,
	POSTSCRIPTION_CONTENT varchar2(2000) CONSTRAINT POSTSCRIPTION_CONTENT_NN NOT NULL,
	POSTSCRIPTION_REGDATE date CONSTRAINT POSTSCRIPTION_REGDATE_NN NOT NULL,
	POSTSCRIPTION_GRADE number(1) CONSTRAINT POSTSCRIPTION_GRADE_NN NOT NULL,
	POSTSCRIPTION_ACTIVE char(1) DEFAULT 'Y',
	STUDENT_NO number(3) CONSTRAINT STUDENT_NO_NN NOT NULL,
	COURSE_NO number(6) CONSTRAINT COURSE_NO_NN NOT NULL,
	CONSTRAINT POSTSCRIPTION_NO_PK PRIMARY KEY (POSTSCRIPTION_NO)
);


CREATE TABLE PROGRESS
(
	PROGRESS_COMPLETE char(1) DEFAULT 'N',
	STUDENT_NO number(3) CONSTRAINT STUDENT_NO_NN NOT NULL,
	COURSE_VIDEO_NO number(4,0) CONSTRAINT COURSE_VIDEO_NO_NN NOT NULL
);


CREATE TABLE QNA
(
	QNA_NO number(4,0) CONSTRAINT QNA_NO_NN NOT NULL,
	QNA_TITLE varchar2(100) CONSTRAINT QNA_TITLE_NN NOT NULL,
	QNA_QUES_CONTENT varchar2(2000) CONSTRAINT QNA_QUES_CONTENT_NN NOT NULL,
	QNA_QUES_DATE date DEFAULT SYSDATE,
	QNA_ANS_CONTENT varchar2(500),
	QNA_ANS_REGDATE date DEFAULT SYSDATE,
	QNA_ACTIVE char(1) DEFAULT 'Y',
	COURSE_NO number(6) CONSTRAINT COURSE_NO_NN NOT NULL,
	STUDENT_NO number(3) CONSTRAINT STUDENT_NO_NN NOT NULL,
	CONSTRAINT QNA_NO_PK PRIMARY KEY (QNA_NO)
);


CREATE TABLE STUDENT
(
	STUDENT_NO number(3) CONSTRAINT STUDENT_NO_NN NOT NULL,
	STUDENT_NAME varchar2(100) CONSTRAINT STUDENT_NAME_NN NOT NULL,
	STUDENT_EMAIL varchar2(256) CONSTRAINT STUDENT_EMAIL_NN NOT NULL CONSTRAINT STUDENT_EMAIL_UK UNIQUE,
	STUDENT_PWD char(64) CONSTRAINT STUDENT_PWD_NN NOT NULL,
	STUDENT_PHONE varchar2(20),
	STUDENT_POINT number(6),
	USER_TYPE char(1) DEFAULT 'S',
	CONSTRAINT STUDENT_NO_PK PRIMARY KEY (STUDENT_NO)
);


CREATE TABLE TECH
(
	TECH_NO number(4,0) CONSTRAINT TECH_NO_NN NOT NULL,
	TECH_TITLE varchar2(100) CONSTRAINT TECH_TITLE_NN NOT NULL,
	TECH_QUES_CONTENT varchar2(2000) CONSTRAINT TECH_QUES_CONTENT_NN NOT NULL,
	TECH_QUES_REGDATE date DEFAULT SYSDATE,
	TECH_ANS_CONTENT varchar2(500),
	TECH_ANS_REGDATE date DEFAULT SYSDATE,
	TECH_ACTIVE char(1) DEFAULT 'Y',
	STUDENT_NO number(3) CONSTRAINT STUDENT_NO_NN NOT NULL,
	CONSTRAINT TECH_NO_PK PRIMARY KEY (TECH_NO)
);



/* Create Foreign Keys */

ALTER TABLE COURSE_VIDEO
	ADD CONSTRAINT COURSE_VIDEO_COURSENO_FK FOREIGN KEY (COURSE_NO)
	REFERENCES COURSE (COURSE_NO)
;


ALTER TABLE ENROLMENT
	ADD CONSTRAINT ENROLMENT_COURSENO_FK FOREIGN KEY (COURSE_NO)
	REFERENCES COURSE (COURSE_NO)
;


ALTER TABLE POSTSCRIPTION
	ADD CONSTRAINT POSTSCRIPTION_COURSENO_FK FOREIGN KEY (COURSE_NO)
	REFERENCES COURSE (COURSE_NO)
;


ALTER TABLE QNA
	ADD CONSTRAINT QNA_COURSENO_FK FOREIGN KEY (COURSE_NO)
	REFERENCES COURSE (COURSE_NO)
;


ALTER TABLE PROGRESS
	ADD CONSTRAINT PROGRESS_VIDEONO_FK FOREIGN KEY (COURSE_VIDEO_NO)
	REFERENCES COURSE_VIDEO (COURSE_VIDEO_NO)
;


ALTER TABLE COURSE
	ADD CONSTRAINT COURSE_DEPTNO_FK FOREIGN KEY (DEPT_NO)
	REFERENCES DEPT (DEPT_NO)
;


ALTER TABLE COURSE
	ADD CONSTRAINT COURSE_LECTURERNO_FK FOREIGN KEY (LECTURER_NO)
	REFERENCES LECTURER (LECTURER_NO)
;


ALTER TABLE ENROLMENT
	ADD CONSTRAINT ENROLMENT_STUDENTNO_FK FOREIGN KEY (STUDENT_NO)
	REFERENCES STUDENT (STUDENT_NO)
;


ALTER TABLE POINT
	ADD CONSTRAINT POINT_STUDENTNO_FK FOREIGN KEY (STUDENT_NO)
	REFERENCES STUDENT (STUDENT_NO)
;


ALTER TABLE POSTSCRIPTION
	ADD CONSTRAINT POSTSCRIPTION_STUDENTNO_FK FOREIGN KEY (STUDENT_NO)
	REFERENCES STUDENT (STUDENT_NO)
;


ALTER TABLE PROGRESS
	ADD CONSTRAINT PROGRESS_STUDENTNO_FK FOREIGN KEY (STUDENT_NO)
	REFERENCES STUDENT (STUDENT_NO)
;


ALTER TABLE QNA
	ADD CONSTRAINT QNA_STUDENTNO_FK FOREIGN KEY (STUDENT_NO)
	REFERENCES STUDENT (STUDENT_NO)
;


ALTER TABLE TECH
	ADD CONSTRAINT TECH_STUDENTNO_FK FOREIGN KEY (STUDENT_NO)
	REFERENCES STUDENT (STUDENT_NO)
;



