create sequence LECTURER_NO_SEQ START WITH 1 INCREMENT BY 1 maxvalue 999 nocache;
create sequence DEPT_NO_SEQ START WITH 1 INCREMENT BY 1 maxvalue 99 NOCACHE;
create sequence COURSE_NO_SEQ start with 1 increment by 1 maxvalue 999999 cache 100;
create sequence ENROLLMENT_NO_SEQ start with 1 increment by 1 maxvalue 999999 cache 100;
create sequence NOTICE_NO_SEQ start with 1 increment by 1 maxvalue 9999 nocache;
create sequence TECH_NO_SEQ start with 1 increment by 1 maxvalue 9999 nocache;
create sequence QNA_NO_SEQ start with 1 increment by 1 maxvalue 9999;
create sequence STUDENT_NO_SEQ start with 1 increment by 1 maxvalue 999 nocache;
create sequence COURSE_VIDEO_NO_SEQ start with 1 increment by 1 maxvalue 9999 nocache;
create sequence POSTSCRIPTION_NO_SEQ start with 1 increment by 1 maxvalue 9999 nocache;